context:
  name: lamin_cli
  version: "1.5.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lamin_cli-${{ version }}.tar.gz
  sha256: be1eb99ab0eadaaeaf914685c90ea4618f1af7909c9afda405d3bbe6cba4106e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - lamin = lamin_cli.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=${{ python_min }}
    - rich-click >=1.7
    - lamindb_setup

tests:
  - python:
      imports:
        - lamin_cli
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - lamin --help

about:
  summary: Lamin CLI.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/laminlabs/lamin-cli

extra:
  recipe-maintainers:
    - hadim
